version: "2"
run:
  concurrency: 4
  go: "1.21"
  tests: false
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unused
    - whitespace
linters-settings:
    depguard:
      rules:
        deny_deprecated:
          deny:
            - pkg: io/ioutil
              desc: io/ioutil is deprecated, use io and os packages instead
    funlen:
      lines: 100
      statements: 50
    gocritic:
      disabled-checks:
        - ruleguard
        - unnamedResult
        - whyNoLint
        - commentedOutCode
        - hugeParam
      enabled-tags:
        - diagnostic
        - performance
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
        - atomic
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - errorsas
        - fieldalignment
        - findcall
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shift
        - sigchanyzer
        - sortslice
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
    lll:
      line-length: 120
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    staticcheck:
      checks:
        - all
issues:
  exclude-use-default: false
  exclude-rules:
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - revive
        text: package-comments
      - linters:
          - staticcheck
        text: ST1000
      - linters:
          - revive
        text: exported.*should have comment
      - linters:
          - revive
        text: receiver-naming
      - linters:
          - revive
        text: unexported-return
      - linters:
          - revive
        text: var-naming.*should be.*ID
      - linters:
          - revive
        text: "method Id should be ID"
        path: internal/eventproc/eventhub/waiters/timer.go
  exclude-dirs:
      - generated
      - .generated
      - examples
      - third_party
      - builtin
  exclude-files:
      - mock_.*\.go$
      - .*\.pb\.go$
      - .*_mock\.go$
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
