run:
  concurrency: 4
  allow-parallel-runners: true
  timeout: 10m
  deadline: 19m
  tests: false
  skip-dirs:
    - ent
  skip-files:
    - mock_*.go
    - .*.pb.go

issues:
  exclude-use-default: false
  errcheck:
    check-type-assertions: true
    check-blank: true
  exclude-rules:    
    - linters:
        - lll
      source: "^//go:generate "

linters-settings:
  enable-all: true
  gocritic:
    enabled-tags:      
     - diagnostic    
     - performance   
     - experimental  
     - opinionated
    disabled-checks:  
      - ruleguard
      - unnamedResult
      - whyNoLint
      - commentedOutCode
  gosimple:
    go: "1.22"
    checks: ["all"]
  staticcheck:
    go: "1.22"
    checks: ["all"]

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck    
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - exportloopref
    - gocritic
    - gocyclo
    # - goerr113
    - goprintffuncname
    - gosec
    - gosimple
    - ineffassign    
    - misspell
    - nakedret
    - nestif
    - prealloc
    - staticcheck
    - testpackage
    - typecheck
    - unconvert
    - unused
    - whitespace
    - nolintlint
    # - wsl
    - govet
    # - depguard
    # - revive
    # - godot
    # - godox
    # - stylecheck
    - goimports
    # - gofmt
    # - lll
    # - gomnd
    # - deadcode deprecated
    # - varcheck deprecated    
    # - rowserrcheck is disabled because of generics
    # - structcheck deprecated
    # - scopelint deprecated
    # - maligned deprecated
    # - unparam # "ломает" ent.go
    # - interfacer # deprecated "ломает" ent.go
    # - bodyclose "ломает" ent.go
    
