package foundation

import (
	"strings"

	"github.com/dr-dobermann/gobpm/pkg/errs"
	"github.com/dr-dobermann/gobpm/pkg/model/options"
)

const (
	// PlainText represents the plain text MIME type.
	PlainText = "text/plain"
)

type (
	// baseConfig holds configuration for BaseElement building
	baseConfig struct {
		id   string
		docs []*Documentation
	}

	// BaseOption represents a function option for configuring BaseConfig.
	BaseOption func(*baseConfig) error
)

// Validate implements options.Configurator interface.
func (bc *baseConfig) Validate() error {
	return nil
}

// Option marks BaseOption as an options.Option; NewBaseElement applies it by
// calling the func directly after its type-switch matches.
func (BaseOption) Option() {}

// WithID updates id field in BaseConfig.
func WithID(id string) options.Option {
	f := func(bc *baseConfig) error {
		id = strings.Trim(id, " ")
		if id == "" {
			return errs.New(
				errs.M("empty id isn't allowed (omit WithID to set autogenerated Id)"),
				errs.C(errorClass, errs.EmptyNotAllowed))
		}

		bc.id = id

		return nil
	}

	return BaseOption(f)
}

// WithDoc updates docs element of BaseConfig.
func WithDoc(text, format string) options.Option {
	f := func(bc *baseConfig) error {
		bc.docs = append(bc.docs, newDoc(text, format))

		return nil
	}

	return BaseOption(f)
}

// baseElement creates a new BaseElement from BaseConfig.
func (bc *baseConfig) baseElement() *BaseElement {
	return &BaseElement{
		id:   bc.id,
		docs: bc.docs,
	}
}
