package instance

import (
	"testing"

	"github.com/dr-dobermann/gobpm/internal/instance/checkpoint"
	"github.com/stretchr/testify/require"
)

// TestRestoredTrackRejectsEmptyID covers restoredTrack's identity guard, which
// FIX-035 §8.3 left outstanding. A checkpoint whose track record carries no id
// is corrupt: foundation.WithID rejects an empty id, and restore must fail
// cleanly and say which record was bad rather than rebuild a track with an
// autogenerated identity that matches nothing in the recorded graph.
//
// node and inst are nil deliberately — the guard is the first statement in
// restoredTrack, so neither is dereferenced on this path, and passing nil
// proves that ordering rather than assuming it.
func TestRestoredTrackRejectsEmptyID(t *testing.T) {
	tr, err := restoredTrack(nil, nil, &checkpoint.TrackRecord{ID: ""})

	require.Error(t, err)
	require.Nil(t, tr)
	require.ErrorContains(t, err, "couldn't rebuild track identity")
}
