name: check
on: 
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54

      - name: Build
        run: go build -v ./...

      - name: Load mockery
        run: go install github.com/vektra/mockery/v2@v2.43.2

      - name: Generate mockery
        run mockery

      - name: Test
        run: go test -v -cover ./...
